namespace AdventOfCode.Generator;

using System.Collections.Immutable;
using System.Diagnostics;
using System.Globalization;
using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

[Generator]
public class AoCDayDependencyInjectionGenerator : IIncrementalGenerator
{
    private readonly static CultureInfo _dutchCulture = new("nl-NL");

    private const string _baseInterfaceName = "IAdventOfCodeDay";
    private const string _markerAttribute = "AdventOfCodeDayAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var providers = context.SyntaxProvider.CreateSyntaxProvider(
            predicate:
            static (node, _) => node is ClassDeclarationSyntax
            {
                BaseList: not null
            },
            transform: static (ctx, _) =>
            {
                if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not INamedTypeSymbol symbol)
                {
                    return null;
                }

                var attribute = symbol.GetAttributes().FirstOrDefault(x => x.AttributeClass?.Name == _markerAttribute);

                if(attribute is null)
                {
                    return null;
                }

                var targetInterface = symbol.Interfaces.FirstOrDefault(x => x.Name == _baseInterfaceName);

                return targetInterface is not null
                    ? new AdventOfCodeModel
                    {
                        ImplementationName = symbol.ToString(),
                        InterfaceName = targetInterface.ToString(),
                        Key = $"{attribute.ConstructorArguments[0].Value}-{attribute.ConstructorArguments[1].Value}",
                    }
                    : null;
            });

        var collect = providers.Where(x => x is not null).Collect();

        context.RegisterSourceOutput(collect, Emit!);

        // Register the attribute source
        context.RegisterPostInitializationOutput(i =>
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.AppendLine($"// Auto-generated by Christmas elves on {DateTime.Now.ToString(_dutchCulture.DateTimeFormat)}");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("namespace AdventOfCode.Attributes;");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("#pragma warning disable CS9113");
            stringBuilder.AppendLine($"public class {_markerAttribute} (int year, int day): System.Attribute {{ }}");
            stringBuilder.AppendLine("#pragma warning restore CS9113");

            i.AddSource("AdventOfCodeDayAttribute.g.cs", stringBuilder.ToString());
        });
    }

    private void Emit(SourceProductionContext context, ImmutableArray<AdventOfCodeModel> models)
    {
        var stringBuilder = new StringBuilder();
        stringBuilder.AppendLine($"// Auto-generated by Christmas elves on {DateTime.Now.ToString(_dutchCulture.DateTimeFormat)}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("namespace AdventOfCode.DependencyInjection;");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("using AdventOfCode.Solutions;");
        stringBuilder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("public static class AdventOfCodeDayDependencyInjection");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("    public static void AddAdventOfCodeDays(this IServiceCollection services)");
        stringBuilder.AppendLine("    {");

        foreach (var model in models)
        {
            stringBuilder.AppendLine($"        services.AddKeyedScoped<{model.InterfaceName}, {model.ImplementationName}>(\"{model.Key}\");");
        }

        stringBuilder.AppendLine("    }");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("  public static IAdventOfCodeDay GetAdventOfCodeDay(this IServiceScope scope, int year, int day)");
        stringBuilder.AppendLine("  {");
        stringBuilder.AppendLine("      return scope.ServiceProvider.GetRequiredKeyedService<IAdventOfCodeDay>($\"{year}-{day}\");");
        stringBuilder.AppendLine("  }");
        stringBuilder.AppendLine("}");

        context.AddSource("AdventOfCodeDayDependencyInjection.g.cs", stringBuilder.ToString());
    }

    private record AdventOfCodeModel
    {
        public string ImplementationName { get; set; } = string.Empty;

        public string InterfaceName { get; set; } = string.Empty;

        public string Key { get; set; } = string.Empty;
    }
}
